### ISSUE TITLE
[BUG] - Error due to invalid buildings in blueprint

### ISSUE THREAD

**Issue by mczz25** [kremnev8/DSP-Mods#61] opened 2023-01-24 06:07 UTC
**Describe the bug**
An error prompt appears when copying the blueprint, and the blueprint cannot be copied after it appears

**To Reproduce**
1. Copy Blueprint
2. See error

**Expected behavior**
Can copy normally without error prompt

**Log files**
[Error  : Unity Log] System.NullReferenceException: Object reference not set to an instance of an object
  at BlueprintTweaks.UIStationPanel.OnUpdate () [0x00034] in <1d2347b3fe034f34b7d5a8bf1abc4589>:0
  at BlueprintTweaks.UIBlueprintPanel.RefreshUI () [0x00020] in <1d2347b3fe034f34b7d5a8bf1abc4589>:0
  at BlueprintTweaks.UIBlueprintInspectorPatch.OnRefresh (UIBlueprintInspector __instance, System.Boolean refreshComponent) [0x00090] in <1d2347b3fe034f34b7d5a8bf1abc4589>:0
  at UIBlueprintInspector.Refresh (System.Boolean forModify, System.Boolean refreshComponent, System.Boolean refreshCode) [0x00a6e] in <c63ca23bdae94e4485ecdf93f54e107d>:0
  at BuildTool_BlueprintCopy.RefreshBlueprintData () [0x00041] in <c63ca23bdae94e4485ecdf93f54e107d>:0
  at BuildTool_BlueprintCopy.Operating () [0x0020e] in <c63ca23bdae94e4485ecdf93f54e107d>:0
  at BuildTool_BlueprintCopy._OnTick (System.Int64 time) [0x00006] in <c63ca23bdae94e4485ecdf93f54e107d>:0
  at BuildTool._GameTick (System.Int64 time) [0x000cf] in <c63ca23bdae94e4485ecdf93f54e107d>:0

**Screenshots**
![Picture 1](https://user-images.githubusercontent.com/122346770/214223149-cc725bd9-2977-46a7-bee5-9e77340be7db.png)
![Picture 2](https://user-images.githubusercontent.com/122346770/214223270-dfcc4e18-117b-4d52-8b5f-18f470f4dad7.png)

**Comment by kremnev8** [comment] 2023-01-24 10:47
I was unable to reproduce your error. However I do think I know the likely cause (Corrupt buildings). Can you please try this test build and determine if your issues persist?
[kremnev8-BlueprintTweaks-1.5.10.zip](https://github.com/kremnev8/DSP-Mods/files/10488770/kremnev8-BlueprintTweaks-1.5.10.zip)

**Comment by kremnev8** [comment] 2023-12-23 19:07
Closing since I can't reproduce the issue, and issue submitter didn't add further info

**Closed by kremnev8** 2023-12-23 19:07 UTC
Labels: bug, Blueprint Tweaks
