### ISSUE TITLE
[BUG] - Storage container placed /Better Machines mod

### ISSUE THREAD

**Issue by Sheepiodas** [kremnev8/DSP-Mods#96] opened 2024-01-31 13:02 UTC
Whenever I placed anything a storager container gets placed. I cant delete or move it. Furthermore my construction drones are removed.
And an Error appears together with the mod.

I tried it with a new savegame and a used one, but the bug still happens.

Is this mod still usable? because it was last updated 10 months ago
Thank you :)

Modlist:
BepInEx
TransferInfo
Bottleneck
AssemblerUI
Power_Network_Manager
SplitterOverBelt
UnlimitedFoundations
LDBTool
DSPModSave
CommonAPI
RebindBuildBar
BetterMachines
DSP_Infinite_Resource_Nodes
CruiseAssist
CloseError

![grafik](https://github.com/kremnev8/DSP-Mods/assets/158290386/9f324bb1-5a89-418c-a3a9-63ff603eb071)

![grafik](https://github.com/kremnev8/DSP-Mods/assets/158290386/c73a94d7-414f-408e-8833-7ff87ca2422e)

**Comment by VerteDragonne** [comment] 2024-02-02 20:12
In short, no, they're broken. I already submitted a ticket for this error, and Krem said the mods are outdated, and to wait for an update.

**Comment by kremnev8** [comment] 2024-02-03 05:33
Closing as duplicate of #94

**Closed by kremnev8** 2024-02-03 05:33 UTC
Labels: bug, duplicate
