### ISSUE TITLE
[BUG] - BlueprintTweaks Error, MissingMethodException

### ISSUE THREAD

**Issue by quning19** [kremnev8/DSP-Mods#97] opened 2024-02-02 15:58 UTC
**Describe the bug**
Use blueprint or press ctrl + v show error.

**Log files**
```ini
An error has occurred! Game version 0.10.29.21904
27 Mods used: [DSPAllPlanetInfo1.1.10] [DSPAutoSorter1.2.11] [DSPCompass0.0.5] [DSP Mod Save1.2.1] [DSPMarker0.0.9] [DSPRecipeFinder0.0.7] [DSPStarMapMemo0.0.5] [DSPStationInfo0.4.9] [NebulaMultiplayerModApi1.3.1.3] [Bottleneck1.1.0] [LSTM0.8.7] [PlanetFinder1.1.3] [SplitterOverBelt1.1.6] [BulletTime1.4.3] [SphereEditorTools2.2.3] [Assembler UI Speed Info Mod2.3.0.0] [LDBTool3.0.1] [DSP Common API1.6.4.0] [Common API Nebula Compatibility1.6.4.0] [AutoShuttleSetup1.8.0] [Blueprint Tweaks1.6.2] [Blueprint Tweaks Installation Checker1.6.2] [ErrorAnalyzer1.0.0] [FactoryLocator1.2.1] [MinerInfo1.1.2] [StatsUITweaks1.4.1] [CruiseAssist0.0.37] 
System.MissingMethodException: void UIBlueprintInspector.Refresh(bool,bool,bool)
  at BuildTool_BlueprintPaste.DeterminAnchorType () [0x000d8] in0 
  at BuildTool_BlueprintPaste.OperatingPrestage () [0x0013e] in0 
  at BuildTool_BlueprintPaste._OnTick (System.Int64 time) [0x00050] in0 
  at BuildTool._GameTick (System.Int64 time) [0x000cf] in0 
== Related patches on the stack ==
DeterminAnchorType(Postfix): static void BlueprintTweaks.Patches.BuildTool_BlueprintPaste_Patch::OnChangedAnchor(BuildTool_BlueprintPaste __instance, bool __result)
OperatingPrestage(Transpiler): static var BlueprintTweaks.BlueprintPastePatch::OperatingPrestagePatch(var instructions)
_OnTick(Postfix): static void BlueprintTweaks.BlueprintPasteExtension::OnUpdate(BuildTool_BlueprintPaste __instance)
```

**Screenshots**
![DSPGAME_sZl4gOrafW](https://github.com/kremnev8/DSP-Mods/assets/409307/996b7318-78a8-40c7-8de5-90769499dfab)

**Comment by kremnev8** [comment] 2024-02-02 16:44
Thanks for your report.
The issue is resolved in v1.6.3

**Closed by kremnev8** 2024-02-02 16:44 UTC
Labels: bug
