### ISSUE TITLE
[BUG][BlueprintTweaks] - Mirroring a fractionator makes it unable to reconnect belts

### ISSUE THREAD

**Issue by MichaelKim0407** [kremnev8/DSP-Mods#55] opened 2022-09-17 09:40 UTC
**Describe the bug**
When a fractionator has both input and output belts connected, mirroring it and then deleting the output belt will render the fractionator unusable.

**To Reproduce**
1. Put down a fractionator with both input and output belts connected.
2. Copy, mirror and paste.
3. Delete the output belt in the mirror.
4. Try to re-add the output belt. It will say "port occupied". See screenshot. This makes the fractionator unusable.

**Expected behavior**
I should be able to add an output belt.

**Screenshots**
![1366540_20220917023312_1](https://user-images.githubusercontent.com/2630527/190850446-e80aca4e-7cbb-48eb-ac1a-29f15c455c05.png)

**Comment by kremnev8** [comment] 2022-09-19 07:21
Thanks for reporting this. Unfortunately I don't have a lot of time right now for modding this game, so I can't say when I will get to fixing this.

**Comment by kremnev8** [comment] 2022-09-27 14:11
After short investigation I believe issues #54 and #55 have the same root cause, not correctly mirroring port ID's. So I will close this one as duplicate.

**Closed by kremnev8** 2022-09-27 14:11 UTC
Labels: bug, duplicate
