### ISSUE TITLE
[BUG] NRE in BuildTool_BlueprintCopy.ArrangeSelection()

### ISSUE THREAD

**Issue by TassadarSC** [kremnev8/DSP-Mods#44] opened 2022-02-15 16:35 UTC
![Dyson Sphere Program 2022_2_16 0_22_25](https://user-images.githubusercontent.com/99750920/154106497-8c85217b-baaa-4dfa-9768-b409a67feb3f.png)

**Comment by TassadarSC** [comment] 2022-02-17 12:12
可能是在我用蓝图画到机器人采集树和石头的采集条石触发的
还有在使用蓝图时有时会强制重叠建造，我在用蓝图建造地基时会看不清楚是否建造导致连续使用数倍的地基
It could have been triggered by the strips of stone that I drew with Blueprints to collect trees and stones from robots, and sometimes overlapping constructions were sometimes forced when using Blueprints, and when I built foundations with Blueprints, I couldn't see if building foundations that resulted in several times the continuous use

**Comment by Seqan01** [comment] 2022-05-01 01:13
Hi! This looks like the same error that happens when I try to blueprint foundation and the blueprint jumps across tropic lines, thus scuffing it and throwing this error. Will verify.

**Comment by kremnev8** [comment] 2023-12-23 19:41
Due to lack of information, and me unable to reproduce the issue, I will close it.
If you or someone else still experiences this issue, feel free to reopen with more info on reproduction steps.

**Closed by kremnev8** 2023-12-23 19:41 UTC
Labels: bug
