### ISSUE TITLE
[BUG] BlueprintTweaks - Cannot paste blueprint foundations to different lateral bands

### ISSUE THREAD

**Issue by AlJoelson** [kremnev8/DSP-Mods#50] opened 2022-05-17 13:26 UTC
**Describe the bug**
When pasting a blueprint containing foundations into a different lateral band than the one the blueprint was originally created in, the foundations will not appear in the intended space but will instead warp to the other side of the planet.

**To Reproduce**
1. Create a blueprint containing foundations in one lateral band (i.e. the tropics).
2. Paste the blueprint into a different lateral band (i.e. the equator or outer equator).
3. Take a look at where the foundations should appear. They will not appear there.
4. Travel 33.33% of the way across the band either east or west (will change depending on which bands you've changed between).
5. You will eventually find the foundations in a strange, different spot.

**Expected behavior**
Foundations should appear in the correct location.

**Log files**
[LogOutput.log](https://github.com/kremnev8/DSP-Mods/files/8708632/LogOutput.log)

**Screenshots**
![bl](https://user-images.githubusercontent.com/6069951/168821634-86534910-0f86-4477-8ee5-da621ae311e1.jpg)

**Additional context**
In testing possible causes, I've also tried running the game with only the BlueprintTweaks mod active (and its prerequisites).

**Comment by kremnev8** [comment] 2022-09-27 14:13
I was unable to reproduce your issue, so I will close it.

**Closed by kremnev8** 2022-09-27 14:13 UTC
Labels: bug
